# SwiftLint configuration for swift-rfc-3986
# Inherits from the shared parent configuration in swift-standards

parent_config: https://raw.githubusercontent.com/swift-standards/swift-standards/main/.swiftlint.yml

# Package-specific overrides
disabled_rules:
  - cyclomatic_complexity
  - empty_string
  - force_try
  - opening_brace
  - orphaned_doc_comment
